server:
  port: 8081
spring:
  security:
    user:
      name: user
      roles: user
      password: 123456
    jwt:
      key: dcx
      expire: 1
  data:
    redis:
      host: 192.168.137.129
      port: 6379